export const PHOTO_LOADING = "PHOTO_LOADING";
export const PHOTO_LOADING_SUCCESS = "PHOTO_LOADING_SUCCESS";
export const PHOTO_LOADING_ERROR = "PHOTO_LOADING_ERROR";

export const DELETE_PHOTO = "DELETE_PHOTO";
export const DELETE_PHOTO_SUCCESS = "DELETE_PHOTO_SUCCESS";
export const DELETE_PHOTO_ERROR = "DELETE_PHOTO_ERROR";

export const EDIT_PHOTO = "EDIT_PHOTO";
export const EDIT_PHOTO_SUCCESS = "EDIT_PHOTO_SUCCESS";
export const EDIT_PHOTO_ERROR = "EDIT_PHOTO_ERROR";
